### ISSUE TITLE
Error with the cmake at new version of gnuradio 3.8

### ISSUE THREAD

**Issue by CastilloDelacroix** [balint256/gr-baz#65]
Hi, I have problem's with de cmake compilation at the new version of GNU-RADIO 3.8. I really need help please.
 I attach de Cmake error's files.

The error is:

lucas@lucas:~/Bloques/gr-baz/build$ cmake ..
-- Build type not specified: defaulting to release.
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.35") found components: system thread
-- Found LOG4CPP: /usr/lib/x86_64-linux-gnu/liblog4cpp.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'gmp'
-- Found gmp, version 6.2.0
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmpxx.so
-- Checking for module 'mpir >= 3.0'
-- No package 'mpir' found
-- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR)
-- Found MPLIB: /usr/lib/x86_64-linux-gnu/libgmpxx.so
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.71.0") found components: date_time program_options filesystem system regex thread unit_test_framework
-- Found VOLK: Volk::volk
-- User set python executable /usr/bin/python3
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.5")
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so (found suitable exact version "3.8.5")
CMake Error at CMakeLists.txt:138 (message):
GnuRadio Core required to compile baz

-- Configuring incomplete, errors occurred!
See also "/home/lucas/Bloques/gr-baz/build/CMakeFiles/CMakeOutput.log".
See also "/home/lucas/Bloques/gr-baz/build/CMakeFiles/CMakeError.log".

This "GnuRadio Core required to compile baz" is extremly rare. GnuRadios it's install correctly.

[CMakeError.log](https://github.com/balint256/gr-baz/files/5570535/CMakeError.log)
[CMakeOutput.log](https://github.com/balint256/gr-baz/files/5570536/CMakeOutput.log)

I have installed GnuRadio companion - 3.8.1.0 in Ubuntu 20.04.1 LTS focal with core 5.4.0-52-generic

**Comment by alphafox02** [comment]
Hello. I just experienced the same thing but two things you need to change. First the main Cmake file is symbolic linked to the 3.7 Cmake txt file so change that link or remove and rename the 3.8 file to 3.7.. but still after that the 3.8 file refers to gnuradio 3.9 (didn’t make sense) so I opened the 3.8 txt file and changed 3.9 to 3.8. Everything then built, but I’m not familiar with gr-baz and I also have not tested anything. These steps at least allow me to build and install with gnuradio 3.8 and DragonOS Focal.

**Comment by CastilloDelacroix** [comment]
Hello, Thanks. This solve the problem, and the gr-baz was build correctly but at the moment of use in gnu-radio only one block of the gr-baz blocks appear in the blocks availables. I attached one screenshot that show this.


![image](https://user-images.githubusercontent.com/64417870/103469397-052e4c80-4d43-11eb-9172-b4a7a6022c03.png)

**Comment by alphafox02** [comment]
No problem and after looking further at the source code I can see the developer intended for only that to be installed in gnuradio 3.8 is detected and everything else If 3.7 is detected. 

I suspect because almost all blocks are not upgraded to QT and instead the old format which does not work in gnuradio 3.8.

So if you have a distro with gnuradio 3.7 you will see a lot more installed but even then it seems like some of the flow graphs are out of date. For sure the OP25 is meant for a really old version of gnuradio and requires and old version of OP25 to patch. 

I hope the developer will maybe find time to bring everything up to date?

**Comment by solomonbstoner** [comment]
Thank you for posting this. I had this same error. In addition, the `CMakeError.txt` made it seem like `-lpthreads` was the issue.
```
src.c:(.text+0x46): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x52): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x5e): undefined reference to `pthread_cancel'
/usr/bin/ld: src.c:(.text+0x6f): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
```

I did what @alphafox02 said...
> Hello. I just experienced the same thing but two things you need to change. First the main Cmake file is symbolic linked to the 3.7 Cmake txt file so change that link or remove and rename the 3.8 file to 3.7.. but still after that the 3.8 file refers to gnuradio 3.9 (didn’t make sense) so I opened the 3.8 txt file and changed 3.9 to 3.8. Everything then built, but I’m not familiar with gr-baz and I also have not tested anything. These steps at least allow me to build and install with gnuradio 3.8 and DragonOS Focal.
 
... and modified the `CMakeLists-3.8.txt` file:
```diff
-find_package(Gnuradio "3.9" REQUIRED)
+find_package(Gnuradio "3.8" REQUIRED)
```

gr-baz compiled fine with GR 3.8 then.
